name: PR # Checks the PR title is of the correct format

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main_v1:
    name: validate title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.6 # cspell:disable-line
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
